# Site settings
title: "DenverBricks.org"
email: infor@denverbricks.org
description: >- # this means to ignore newlines until "baseurl:"
  The DenverBricks (also referred to as Colorado DataBricks) user group is a new community initiative designed to bring together all users of the Databricks platform—data engineers, data scientists, analysts, architects, and AI/ML practitioners—from across Colorado.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://emptycupconsulting.github.io" # your GitHub Pages URL
twitter_username: denver_bricks
github_username: 

# Build settings
remote_theme: "mmistakes/minimal-mistakes@latest"
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minimal Mistakes settings
minimal_mistakes_skin: "default" # options: default, air, contrast, dark, dirt, neon, mint, sunrise
locale: "en-US"
timezone: "America/Denver"

# Author settings
author:
  name: "DenverBricks"
  avatar: "/assets/images/avatar.jpg"
  bio: "A short bio about yourself."
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/groups/14811090"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/denver_bricks"
  - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://instagram.com/denverbricks"
  - label: "YouTube"
      icon: "fab fa-youtube"
      url: "https://youtube.com/@denver_bricks"

# Navigation
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
