# Site settings
title: "My Site"
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A brand new GitHub Pages site using the Minimal Mistakes theme.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # your GitHub Pages URL
twitter_username: your_twitter
github_username: yourusername

# Build settings
remote_theme: "mmistakes/minimal-mistakes@latest"
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minimal Mistakes settings
minimal_mistakes_skin: "default" # options: default, air, contrast, dark, dirt, neon, mint, sunrise
locale: "en-US"
timezone: "America/Denver"

# Author settings
author:
  name: "Your Name"
  avatar: "/assets/images/avatar.jpg"
  bio: "A short bio about yourself."
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/yourusername"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/your_twitter"

# Navigation
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
