# --- SITE SETTINGS ---
title: "DenverBricks.org"
email: info@denverbricks.org
description: >-
  The DenverBricks (also referred to as Colorado DataBricks) user group is a new community initiative
  designed to bring together all users of the Databricks platform—data engineers, data scientists,
  analysts, architects, and AI/ML practitioners—from across Colorado.

# Use your custom domain
url: "https://denverbricks.org"
baseurl: "" # always empty with a custom domain

logo: "/assets/images/denver-bricks-logo.png"

# --- THEME & BUILD ---
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# --- LOCALE ---
minimal_mistakes_skin: "default" # options: default, air, contrast, dark, dirt, neon, mint, sunrise
locale: "en-US"
timezone: "America/Denver"

# --- AUTHOR SETTINGS ---
author:
  name: "DenverBricks"
  avatar: "/assets/images/avatar.jpg"
  bio: "Building community, one brick at a time."
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/groups/14811090"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/denver_bricks"
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://instagram.com/denverbricks"
    - label: "YouTube"
      icon: "fab fa-youtube"
      url: "https://youtube.com/@denver_bricks"

# For SEO/social sharing (jekyll-seo-tag)
social:
  name: "DenverBricks"
  links:
    - "https://twitter.com/denver_bricks"
    - "https://github.com/EmptyCupConsulting"
    - "https://www.linkedin.com/groups/14811090"
    - "https://instagram.com/denverbricks"
    - "https://youtube.com/@denver_bricks"

# --- NAVIGATION DEFAULTS ---
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# --- PERMALINKS (cleaner blog URLs) ---
permalink: /:categories/:title/

# --- EXCLUDE (don’t build these) ---
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
